### ISSUE TITLE
Create a simplerdf-body-parser package based on rdf-body-parser

### ISSUE THREAD

**Issue by bergos** [nicola/simplerdf#21]
express applications could use this package to handle request and response graph data with SimpleRDF objects.

**Comment by nicola** [comment]
are you talking about simplerdf-parse?

**Comment by bergos** [comment]
No, a Express middleware like the [rdf-body-parser](https://github.com/rdf-ext/rdf-body-parser). It parsers incoming graphs and creates a SimpleRDF object and attaches it to req.simple. It also attaches the res.sendSimple method to the response to send SimpleRDF objects. It's already on my hdd, but I have to separate it from another project.

**Comment by bergos** [comment]
@nicola I choose the name `rdf-body-parser`, because first it was a parser only middleware. Now it also attaches a `res.sendGraph` method. Do you have a proposal how we could name the middleware? We would have two middlewares. `rdf-*` for "raw" RDF-Ext graph objects and `simplerdf-*` for SimpleRDF objects.

**Comment by nicola** [comment]
@bergos sounds like a great naming pattern!

**Comment by bergos** [comment]
The package is now on [github](https://github.com/bergos/simplerdf-body-parser) and [npm](https://www.npmjs.com/package/simplerdf-body-parser).
