### ISSUE TITLE
Add optional parameter for SimpleRDF to omit withCredentials

### ISSUE THREAD

**Issue by csarven** [nicola/simplerdf#34]
re: https://github.com/rdf-ext/rdf-ext/pull/54 lets an optional parameter to omit or set `withCredentials` to false. Similarly, `SimpleRDF()` should have the optional parameter for it.

**Comment by nicola** [comment]
Implemented in https://github.com/simplerdf/simplerdf/commit/3b81872526fc9f90c5d5c7c86fe5caefe1906796

``` javascript
me.get(iri, {withCredentials: false})
// or
me.get({withCredentials: false})
```

@csarven
