### ISSUE TITLE
Property with multiple values only retains first value.

### ISSUE THREAD

**Issue by csarven** [nicola/simplerdf#4]
If a property has multiple values, it only retains the first one. The expectation is that, an array is returned in the case of multiples (aside: may want to always return an array).

Is this the `TODO` for above https://github.com/nicola/simplerdf/blob/master/index.js#L54 ?

**Comment by csarven** [comment]
Since a subject-property pair may have multiple values, it doesn't make much sense to use `@array` for practically everything in the context. I suggest not bothering with that declarative approach ... if I'm reading the current code correctly.

**Comment by nicola** [comment]
That TODO refers to a different issue which is supporting popping and pushing something from an array should reflect on the graph of the object in the background

**Comment by nicola** [comment]
Use `@array: true` when you define the schema for now :) (please suggest improvements if you have any)

**Comment by csarven** [comment]
Thanks this works.

An improvement is like I said, from the RDF perspective (not vocabulary), since any sp pair can have multiple o values, I suggest treating it as an array by default. There is no need to make the user explicitly declare `"@array": true` in context for each object.

**Comment by nicola** [comment]
Then everything would be an array and we can't do simple things like me.name = "Nicola" since name would be an array..
Is there a way to infer when to do each other?

**Comment by csarven** [comment]
There is a cost which probably can't be avoided, i.e., the user has to deal with either a string or an array at some point; either when it is declared in the context, or checked for later in the code. I personally prefer not to worry about this in the context, i.e., keep the declarations in the context consistent, but handle it in the code instead. This is a better practice in my opinion because the user would have a better handle on the type of object they are dealing with.
