### ISSUE TITLE
Default Serializer

### ISSUE THREAD

**Issue by sylvainlb** [nicola/simplerdf#57]
I'm creating the issue here, but I'm not sure if it's not a defect of rdf-store-ldp.
The server on which I'm working right now only accepts JSON-LD. So I tried passing the right serializer as an option:
`p.save({defaultSerializer: "application/ld+json"})`

But data is still passed in turtle. In fact the option is passed to the `add` of the `LdpStore`, but is not used there.

**Comment by bergos** [comment]
Right now you have to set your own LDPStore with `parsers` and `serializers` options. It should look like this:

```
// have a look inside the package to load only the required parser and to reduce the dependencies
var formats = require('rdf-format-commons')()

var store = new LdpStore({
  parsers: {
    'application/ld+json': formats.parsers['application/ld+json']
  },
  serializers: {
    'application/ld+json': formats.serializers['application/ld+json']
  }
})

var s = new SimpleRDF(context, iri, graph, store)
```

We have already plans to simplify this. There should be a factory, that builds SimpleRDF objects with the defined options.

**Comment by sylvainlb** [comment]
Right, I didn't think of this solution. That should do it for now.

Let me know if I can help with the development. I would have gone with setting the serializer option, but I'm not sure what your plans with this factory thing. Tell me if I can give a hand.

**Comment by bergos** [comment]
I will try to write more details to the issues. Than you can just grab one or more :-)

**Comment by sylvainlb** [comment]
Thanks!

**Comment by sylvainlb** [comment]
Hmmm. I may just be confused, but I couldn't manage to do it.
I'm working in the browser, so I tried to browserify rdf-store-ldp, but LdpStore wasn't available.
If you think of something obvious that I missed, let me know. Otherwise, I'll try again later.
