### ISSUE TITLE
SimpleRDF.prototype.iri updating subject/object per call

### ISSUE THREAD

**Issue by csarven** [nicola/simplerdf#6]
Glancing at `SimpleRDF.prototype.iri`: it uses `updateSubject` and `updateObject` methods which appears to append the results from previous calls. For example:

```
var g = SimpleRDF(context);
g.iri(preferences).get().then(
    function(pf) {
        var s = pf.iri(webid);
        s.workspace.forEach(function(ws) {
            var w = pf.iri(ws);
            console.log(w.rdftype);
        });
    },
    function(reason){}
);
```

will have output an unique array (`w.rdftype`) while including the items from earlier `w`.

If I comment out the calls to `updateSubject` and `updateObject` it works as expected.

Is this a regression bug or intended? My preference is to be able to rely on the graph that's available to me "as is" so I can use it subsequently without updates. If I need to update, I can do that explicitly.

**Comment by bergos** [comment]
@csarven Did you public data from the web? Can add the content of `context`, `preferences` and `webid` to this issue, so I can reproduce it?

Also I'm not sure why you use `var w = pf.iri(ws);` it should be possible to use `ws` as a SimpleRDF object in the loop. Maybe `console.log(ws.rdftype)` without setting the IRI does already what you want.

**Comment by csarven** [comment]
I understand your point, but `ws.rdftype` won't work in this particular case because `ws` is a string. In my actual code, I'm doing `pf.iri(ws).rdftype`. In any case:

You won't be able to reproduce this exactly, but my:

context is here: https://gist.github.com/csarven/ade1ecfd24eca20d9fd4

the preference file is here: https://gist.github.com/csarven/7832822aaddcc57b4157

Essentially the preference file has the webid, which it has several workspaces. The idea is to get a hold of each of the `rdf:type`s of those workspaces.

Removing lines:

```
updateSubject(this._graph, this._iri, iri)
updateObject(this._graph, this._iri, iri)
```

appears to resolve the issue, or at least works as expected. Are these lines really needed?

**Comment by bergos** [comment]
@csarven I think you solved your problem with `.child()`, right? Can we close this issue?

**Comment by csarven** [comment]
Yes, .child() resolved it.
