### ISSUE TITLE
Accessing _iri and _graph

### ISSUE THREAD

**Issue by bergos** [nicola/simplerdf#9]
The `.iri()` and `.graph()` methods return `this` for method chaining. The underscore variables should not be used for reading. A method should be used, so there is no way to write a new value.

The current methods are very useful for method chaining, so we should not change the return value. I would propose to create new methods. I think `.getIri()` and `.getGraph()` are good candidates.

@nicola What do think?

**Comment by nicola** [comment]
no, we can set setters on `.iri` to do nothing after `.iri` is set.

Hold on, why do we not want to provide the possibility of editing it?

**Comment by bergos** [comment]
Sometimes the graph is fetched from an IRI that is not the graph name (e.g. a SPARQL CONSTRUCT query). That requires writing the IRI. I'm not sure about write access to the graph. At the moment `.child()` + `.graph()` can be used to create a new object with the same context. A `.clone()` method would be better.

But the problem is the read access. At the moment it's only possible with `._iri` and `._graph`.

**Comment by nicola** [comment]
solved in latest
